language: python
python:
  - "3.8"
  - "3.9"

services:
  - docker

script:
  - docker compose -f ./docker-compose-test.yml build
  - docker compose -f ./docker-compose-test.yml up -d
  - pip install -r requirements-test.txt
  - pip install .
  - coverage run -m pytest test
  - coverage report -m

after_script:
  - docker compose -f ./docker-compose-test.yml down
  
