language: python
python:
  - "3.7.9"     
  - "3.8"

services:
  - docker

before_script:
  - docker-compose -f ./docker-compose-test.yml build
  - docker-compose -f ./docker-compose-test.yml up -d
  - pip install -r requirements-test.txt
  - pip install .

script:
  - coverage run -m pytest test
  - coverage report -m

after_script:
  - docker-compose -f ./docker-compose-test.yml down
  
