version: '3'
services:
  rabbitmq:
    container_name: ensrabbitmq
    image: 'rabbitmq:3-management-alpine'
    volumes:
      - './rabbitmq_config/rabbit_event_definition.json:/opt/definitions.json:rw'
      - './rabbitmq_config/rabbitmq.config:/etc/rabbitmq/rabbitmq.conf'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - productionsrv   

  event_app:
   build: '.'
   container_name: 'event_app'
   command: "/usr/local/bin/gunicorn --config /app/gunicorn_config.py -b 0.0.0.0:5000 ensembl.production.event.app.main:app"
   ports:
     - "5008:5000"        
   networks:
     - productionsrv 

  celery-process:  
   build: '.'
   ports:
     - "5012:5000"     
   container_name: 'celery-process'
   command: "celery -A ensembl.production.event.celery.tasks worker -l info -Q workflow -n workflow-process@%%h"
   networks:
     - productionsrv

  celery-monitor:  
   build: '.' 
   ports:
     - "5013:5000"      
   container_name: 'celery-monitor'
   command: "celery -A ensembl.production.event.celery.tasks worker -l info -Q monitor -n workflow-monitor@%%h"
   networks:
     - productionsrv     

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.4'
    container_name: elasticsearch
    environment:
      - http.port=9200
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - productionsrv

networks:
  productionsrv:
    driver: bridge         